### PR TITLE
Cache

### PR DESCRIPTION
**Pull request by jschreuder**
As requested by Phil I wrote a first attempt at a Cache implementation. It's been tested by now and should work fine.

Usage example:
    $cache = Cache::factory('test');
    try
    {
        $test = $cache->get();
    }
    catch (Cache_Exception $e)
    {
        // create $test value
        // code below sets expiration to 5 minutes
        $cache->set_contents($test)->set_expiration(5)->set();
    }

### CODE REVIEW

**Comment by huglester** [comment]
Hello everyone :)

I do like Phil's Cache lib. often using it. but can we have a cache lib in Fuel supporting 'tags'?:) 
I think it's LOVELY feature. and a bit bigger projects would definitely need this!

Good luck guys
Jaroslav

**Comment by jschreuder** [comment]
Must admit I have no idea what 'tags' are when talking about caching. Got some more information/usage examples about what that entails?

**Comment by huglester** [comment]
No problem, I will try to explain.. I'll be using Phil's cache lib as an example from: http://philsturgeon.co.uk/code/codeigniter-cache

here we go:
// Uncached model call
[code]$this->blog_m->getPosts($category_id, 'live');[/code]

// cached model call
[code]$this->cache->model('blog_m', 'getPosts', array($category_id, 'live'), 120); // keep for 2 minutes [/code]

So here we cache the result for 120 secods = 2minutes.

What if we could pass: 
[code]$this->cache->model('blog_m', 'getPosts', array($category_id, 'live'), 0, array('posts', 'forum')); // I want to cache it forever [/code]

and for example, now I have function in forum:
[code]function new_post()
{
   //and here I want that all 'caches' with tag 'posts' would be deleted:
   $this->cache->delete_all_by_tag('posts');
}
function new_subforum()
{
   //this would delete both 'posts' and 'forum' tags..
   $this->cache->delete_all_by_tag('posts', 'forums');
}[/code]

I hope you'll now better understand what I mean by saing tags.
Maybe of course some of you have other thought on this?

Sorry I could not give you live example, because I don't have one since did not find a lib for CI wich could do that...

Another example would be for example you have a weather forecast site there you would:
[code]$this->cache->model('weather_m', 'get', array('London'), 0, array('uk', 'county1'));
$this->cache->model('weather_m', 'get', array('Birmingham'), 0, array('uk', 'county2'));
$this->cache->model('weather_m', 'get', array('Wells'), 0, array('uk', 'county1'));
$this->cache->model('weather_m', 'get', array('Oxford'), 0, array('uk', 'county3'));[/code]

so for example if smth bad happens all over UK, i would just: $this->cache->delete_all_by_tag('uk');
if for example it suddenly happened very sunny in som county/counties I would: 
$this->cache->delete_all_by_tag('county1', 'county3');

I hope you have got my mind now... I tried to be informative as I can :) 

added: Sorry, don't know how to add code blocks :/

Thanks,
Jaroslav

**Comment by jschreuder** [comment]
I think I can implement this using the current dependencies functionality in a specialized way. When you add a tag it would add a dependency to an empty file that refreshes when you call that tag to be emptied.

If you don't know dependencies already: a dependency triggers a check on cache loading that looks if any of the other caches the current one "depends on" is either newer or has been deleted, if it was the load function will expire the current cache.

So it wouldn't really be delete_all_by_tag() but more of a expire_all_by_tag().

**Comment by philsturgeon** [comment]
The dynamic syntax for this seems like it might be a little complicated. Do we need to have methods for expirey or just an optional parameter?

Similar to WanWizards Session library we could have Session::get()/set() acting immediately then have the dynamic syntax for the more complicated approach, but again I'm not sure we need the extra methods.

Anybody else got an opinion to throw in here?

**Comment by jschreuder** [comment]
@phil for the get()/set()/call() methods to work static they could take the parameters and create a temporary instance that names by md5(serialize()) on the given contents (or an array with callback and params for call()). That would be very simplified and not really the way I intended it, but that might be exactly offering both the simple and advanced implementations.

EDIT: Also by looking at the examples from your cache lib I realized I didn't implement the call() method correctly, it should always return the contents and do both the get() and set() operations.

EDIT2: I didn't fully think this through, of course you can't set the cache identifier for get()/set() by its contents, there would be very little use to cache something if that would work. That is exactly how it works with the static Cache::call() because you use the callback and params; but the static Cache::get() and Cache::set() need an extra param that sets the identifier.

**Comment by philsturgeon** [comment]
That sounds like a good option. Ideally we can keep things really simple, with more advanced options being available when instantiating a class so you can work with it more.

**Comment by jschreuder** [comment]
I just added a commit that should allow that: 23f08e3 it's untested as I don't have any more time but this should at least make it possible to do the following types of call:

```
try
{
    $test = Cache::get('test');
}
catch (Cache_Exception $e)
{
    // create $test contents
    Cache::set('test', $test, 120);
}
```

Or:

```
$test = Cache::call(array($model, 'getPosts'), $category_id);
```

EDIT: I'll look into a "tags" implementation later.

**Comment by huglester** [comment]
I think you guys already discovered the best way for this. I feel like newbie in such 'big' things. But I think many of us will surely start using this option.
When I have more ideas, I will surely come back here :)
Thanks guys!

**Pull request closed without merging**
