### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by soudai**
1.7　Bug fixes

ViewModel is executed twice

Return value of RESTController is for array

### CODE REVIEW

**Comment by kenjis** [comment]
Don't send PR to master branch. Send it to 1.8/develop.
And you better read "Coding Standards" in FuelPHP Documentaion.

**Comment by soudai** [comment]
I'm sorry

http://fuelphp.com/docs/general/coding_standards.html

I've read

Can I re-PR to 1.8/develop?

**Comment by soudai** [comment]
プルリクエスト先が間違ってるのでCLOSE

**Comment by kenjis** [comment]
I forget to mention about "sign-off". 
Please read https://github.com/fuel/fuel/blob/1.7/master/CONTRIBUTING.md too.

And do not write Japanese here, please. Because most people here can not read it.

**Comment by WanWizard** [comment]
Has been fixed in 1.8/develop, and will be backported to 1.7.1 when that gets released.

**Comment by soudai** [comment]
Thank you.
I am looking forward to the release of 1.7.1.

**Pull request closed without merging**
