### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dudeami0**
Fixed 3 bugs:
- Image transparency with GIF images was turning up black, now turns up transparent
- Backgrounds with JPEGs would remove alpha transparency when no bgcolor was given. This would cause jagged edges on transparent PNGs when outputting as JPEG.
- Outputting non-PNG images as the format they were previously in (Such as a outputting a gif as a gif) would result in a PNG image.

Made sizes() public, and added documentation for it.
Added reload(), and made a config option for persistence (Same thing as calling reload). Added both to the docs.

Few other minor fixes and what not.

### CODE REVIEW

**Comment by dudeami0** [comment]
Ok, that should be it for known bugs at this moment in time... Probably weed out a few more once the RC comes out :p

**Comment by dudeami0** [comment]
And that was an accident... Maybe I should do these in the mornings xD

**Comment by dudeami0** [comment]
And decided to run over the redmine site, fixed bug #69.

**Comment by huglester** [comment]
Hello dudeami :) 
I tried reopen, and get an error like this: http://d.pr/lrg5
controller here: http://scrp.at/I-

P.s. with this fix yes, have no problem with gifs :)

**Comment by dudeami0** [comment]
That should fix it :) Thanks for the heads up

**Comment by huglester** [comment]
Hey :) thanks ,fix one fixes, but here is one more test:
http://scrp.at/Ja

seems using 'preset' , it's test #6 - does not 'reset' the borders, use the code posted above and see how the output looks :)

**Comment by dudeami0** [comment]
Hmm... I'll take a look at it sometime tomorrow, I've had no luck with it so far :p

**Comment by dudeami0** [comment]
And ofcourse the obvious eludes me.

Set the config value 'clear_queue' to true and it should work as expected :p  If not let me know

**Comment by dudeami0** [comment]
Reopening with email fix and docs.

**Pull request closed without merging**
