### PR TITLE
Develop: Assets: Automatically add missing file extension to JavaScript and Stylesheet files

### PR DESCRIPTION
**Pull request by riker09**
As I've posted in the forum I think the Asset class should add a file extension to JavaScript and Stylesheet files if the extension was omitted when calling Asset::css('file') or Asset::js('file'). This behaviour is used at least by Symfony.

### CODE REVIEW

**Comment by philsturgeon** [comment]
This will stop style.php working and force it to be style.php.css, which requires a change to Apache in how .css files are handled... This is why it was avoided in the first place.

**Comment by riker09** [comment]
Okay, this wasn't clear to me from the documentation. I was pondering over the line <?php echo Asset::css('main'); ?>, seems like the documentation really should be changed here.

Anyway, these were my first steps with Git and GitHub. I'm using Netbeans 6.9 but there's currently no offical way to push to GitHub with the "official" nbgit plugin, at least none that I could find. What IDE do you use to develop for Fuel?

**Comment by philsturgeon** [comment]
That was an error in the documentation that has been changed since. I would like to support suffixes if we can think of a way to do it without restricting functionality.

I use Netbeans to write code, GitX to view commits and Terminal for the rest.

**Comment by riker09** [comment]
I think it's rather unusual to create files like main.css.php (although I see the benefits). If people would like their asset files to be parsed by PHP they still could by specifiying the full file name.

I'm closing this pull request, it was a first introduction to the world of GutHub for me. Thank's so far.

**Pull request closed without merging**
