### PR TITLE
Global namespaces fixed + oil update

### PR DESCRIPTION
**Pull request by it-can**
Added some global namespace slashes and updated oil script

### CODE REVIEW

**Comment by WanWizard** [comment]
Technically this wasn't needed, all this code runs in the global namespace. But I agree is cleaner and more consistent.

Have you tested this? The previous commit of this type broke the framework...

**Comment by it-can** [comment]
What did break before then?

I tested these changes on my own project, no problems at this point...

**Comment by WanWizard** [comment]
https://github.com/fuel/core/commit/75ea44310901b0338b8fd3f6df04b08664caba5c

I don't think there's an issue with these, so I'll merge them.

**Comment by it-can** [comment]
Weird, because \HttpException never gave me issues whatsoever... mmm it seems pecl_http package is causing troubles here? http://php.net/manual/en/httprequest.send.php

**Comment by WanWizard** [comment]
Probably.

**Pull request merged**
