### PR TITLE
Change minimum-stability to stable

### PR DESCRIPTION
**Pull request by kenjis**
See https://github.com/fuel/core/issues/1755

### CODE REVIEW

**Comment by kenjis** [comment]
I think it is okay that 1.8/develop branch's `minimun-stabliliy` is `stable`.

If we want to use some packages with stablilty `dev`, we can set them like:

```
"foo/bar": "1.0.*@dev"
```

Or if we want master branch:

```
"foo/bar": "dev-master"
```

dev-master has stability `dev`.

**Comment by WanWizard** [comment]
In any develop branch you would always want dev (so you get the other fuel repo's cloned in the develop branch too, and not as the latest stable). 

Remember that a develop branch is our development environment. If you want to use that for applications, fine, but that shouldn't impact the fact that dev must be default.

**Comment by kenjis** [comment]
Sorry, I don't understand what you exactly want to say.

This PR is for 1.7/master, but if you merge into 1.8/develop (I think you should do it),
it only changes versions of psr/log and composer/installer.

`minimum-stability` is not `version`. It is minimum stability.
See https://igor.io/2013/02/07/composer-stability-flags.html

**Comment by WanWizard** [comment]
Is this still relevant?

**Comment by kenjis** [comment]
Yes, I think at least official release version has minimum-stablility `stable`.

And I also hope that `1.8/develop` has minimum-stablility `stable`. Because I don't want to use composer packages with stability `dev`.  But ff you want to use a package with stability `dev`, you could specify it only to the package in composer.json.

**Pull request closed without merging**
