### PR TITLE
(Image Lib) Some fixes and a few additions

### PR DESCRIPTION
**Pull request by dudeami0**
Bug fixes:
- Transparency in gifs is lost when outputting in GD
- Transparency when outputting jpegs with no bgcolor loses some of the alpha channel in GD
- Outputting non-PNG images as the format they were previously in (Such as a outputting a gif as a gif) would result in a PNG image in ImageMagick driver.
- reload() was not chainable.
- Use of config() in the static reference didn't allow usage with index value pairs.

Few other fixes and such added.

(Update)

More Bug Fixes:
- Fixed bug with saving a blank file without extension.
- Fixed bug with not accepting uppercase extensions.
- Fixed bug with resize() when width and height are supplied (Cropped instead of resized).

Also added inital support for PSDs (Still needs testing) and possibly other formats in imagemagick.

### CODE REVIEW

**Comment by huglester** [comment]
Thanks, this one fixes all my issues :)
lovely lib

**Comment by huglester** [comment]
Hello, 
have one more problem: 
while using save: ->save('filename', 0666); (without the extention)
I get created the file without extension and one with extension... Couldn't find any more troubles :)

**Comment by huglester** [comment]
And one more problem I forgot: 
Fuel\Core\Fuel_Exception [ Error ]: The library does not support this filetype for /var/www/vhosts/vibe/fuel/app/userdata/photos/9_a6636a888e2a38b5630466e2ddaeb400.JPG.

The lib complains about case sensitive image extensions... I think that should be changed :)

imho those are all of my comments on this lib. other than that - works perfectly

**Comment by dudeami0** [comment]
Ok, i'll fix those up sometime tonight

**Comment by jschreuder** [comment]
Could you make this pull request on the new core repo? I can't pull it here...

**Pull request closed without merging**
