### PR TITLE
Fix dsn default charset

### PR DESCRIPTION
**Pull request by gnovaro**
Defining uf8 by default

### CODE REVIEW

**Comment by kenjis** [comment]
Good point!

**Comment by WanWizard** [comment]
It is not needed.

The PDO driver does a set_charset() after creating the connection using the characterset defined in the config of the selected database. And by default, that contains 'utf8'.

**Comment by kenjis** [comment]
@WanWizard 

set_charest() uses `SET NAMES`:
https://github.com/fuel/core/blob/1.8/develop/classes/database/pdo/connection.php#L150

This is bad practice, and causes SQL injection in some charsets like Shift_JIS. Because `SET NAMES` is a command to the SQL session, but is not PDO driver API to set charset. So PDO doesn't know the charsert in the command, doesn't know correct charset. So PDO could mistake escaping if we use charsets which contain escape char(`0x5c` ie `\`) in one character bytes. Some multibyte charset contains `0x5c` in one letter.

Unfortunately there is no API to set charset in PDO. And PDO_MYSQL can set charset in dsn.

**Comment by WanWizard** [comment]
How can

```
SET NAMES 'utf8';
```

cause SQL injection? In any characterset? It would at least require something very funkie in your db config file, and if a hacker manages that, your problems are at a different level from this possible injection...

**Comment by kenjis** [comment]
It is difficult to explain the way injects SQL, but I remember I wrote it in past:
https://github.com/EllisLab/CodeIgniter/pull/606#issuecomment-2529086
Above my comment explains SQL injection in Shift_JIS encoding.

Point is in the world there are charsets which includes 0x5c `\` (escape character) in one letter. And if escaper (in this case PDO) doesn't know correct charset, it breaks strings like that when escaping. Attackers could abuse it to inject.

And PHP manual also warns:

> The method in the below example can only be used with character sets that share the same lower 7 bit representation as ASCII, such as ISO-8859-1 and UTF-8. Users using character sets that have different representations (such as UTF-16 or Big5) must use the charset option provided in PHP 5.3.6 and later versions. 
> http://php.net/manual/en/ref.pdo-mysql.connection.php

 It means ISO-8859-1 and UTF-8 are safe, if we use `SET NAMES`

**Comment by WanWizard** [comment]
https://github.com/zendframework/zf2/issues/4662 suggests it might not be a good idea. A related discussion for CI addresses it the same way: http://ellislab.com/forums/viewthread/212311/#988755

But assuming the PHP docs are right (use the charset parm on the DSN), it's probably better to have the code check if it is present, and if not, simply inject the charset defined in the config? That would avoid you having to define it in two places, and also avoid the confusing situation that you can define Shift_JIS on the DSN, and utf8 as charset (which is then used for dbutil, and for the DB engine itself).

**Comment by kenjis** [comment]
It seems that Zend added charset to DSN: https://github.com/zendframework/zf2/pull/4973/files

Yes, your idea is better. 

But setting charset in DSN is PDO_MySQL specific. PDO_PGSQL does not support (I'm not confirmed the latest code, but there is still no charset in PHP manual: http://php.net/manual/en/ref.pdo-pgsql.connection.php).

**Comment by WanWizard** [comment]
From what I understand, drivers ignore anything in the DSN that they don't need, so it should be save to just add it in the code.

**Comment by WanWizard** [comment]
Added: https://github.com/fuel/core/commit/6e15b9cc970a605907afcb9b1e6fc6f06ea83ffb

**Pull request closed without merging**
