### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dudeami0**
Added an email class based on my Dmail class (which has some code from codeigniters email class). Fully tested as working on Windows 7 64-bit on XAMPP (PHP 5.3.1). Documented and gives credit to codeigniter where needed. Use is almost identical to codeigniters email class:

```
Email::initalize(Array())
    ->to('someone')
    ->from('someone')
    ->html('Set some HTML here')
    ->text('Set some text here')
    ->message('Can optionally use message and set_alt_message()')
    ->send();
Email::print_debugger();
```

### CODE REVIEW

**Comment by philsturgeon** [comment]
Rename initialize to factory and you have yourself a deal!

**Comment by dudeami0** [comment]
Renamed the initialize method to factory. Just noticed I misspelled initialize in the commit, shouldn't matter to much though :p

**Comment by dudeami0** [comment]
To be honest, the package was the first way I understood on how to implement this. Now that I have been looking over the code a bit more, I could make it into a library (Doesn't seem to need a lot of modification).

I split out all the protocol specific (Mail, Sendmail, and Smtp classes) stuff to allow additional protocols to be added as needed. I can modify the code for these to be drivers for the email class.

Licensing isn't a problem. I just use the GPL by default for all of my projects, but I'll just remove the licensing so it falls under Fuels licensing (MIT if I remember correctly). The only thing I don't have the rights to change the licensing on are a few functions in the Emailer class (credit is given in the PHPDocs) from the codeigniter email library.

For the configuration files, I'll move them to core/config.

I also have one question for this. If I make this a library, would the namespace be Fuel then?

**Comment by philsturgeon** [comment]
Exactly right, look at the Session library to see how it all fits together.

**Comment by dudeami0** [comment]
Sorry about the double commit, but would that fit the bill?

**Comment by philsturgeon** [comment]
Forgot to mention, factory should return an instance, so $email = Email::factory(); $email->send(); etc works.

**Comment by dudeami0** [comment]
I'll work on the changes that you mentioned. Currently it returns a single instance, and will return the same instance when called multiple times. Should it return a new instance each time, or is the current way fine?

**Comment by jschreuder** [comment]
The function factory() in Email_Driver isn't a factory. A factory produces objects and may initialize, this function doesn't produce objects it only initializes them after creation. Most sense would be to call it init() or merge with __construct().

Also, as Phil mentioned: the factory in Email class should return a NEW object but not replace the old one in the Email class. That way people can create multiple email objects if needed, or just work with the static usage and have only 1.

**Comment by dudeami0** [comment]
Thanks for clarifying that. I'll work on those changes today and send a commit sometime tonight.

**Comment by philsturgeon** [comment]
If you need to run multiple methods for a class it makes sense to create a dynamic instance so you can chain and work with multiple instances, without nearing to "clear" the static instance.

Libraries in CI always have to be "cleared|" before they can be used again, which is not the best way to do it.

Thanks for being a good sport about the feedback. We have to make sure stuff is right before it gets merged :)

**Comment by dudeami0** [comment]
I'm still learning how the framework works, and the feedback helps a lot :)

Anyways, I'll remove the clear method in the email driver and make the mail, sendmail, and smtp classes extend the main email driver. The reason I did not do this is so protocols could be changed on the fly in CI, but since multiple instances will be created, protocols can be changed by making a new instance.

**Comment by dudeami0** [comment]
Well, I ended up working on it now instead of later :p Something I didn't note in the commit, I added definitions to the config variables in core/config/email.php. Other than that I think this meets the standards, else just let me know what needs to change.

**Comment by umefarooq** [comment]
what about batch sending for multiple emails but separate emails for each recipient for inspiration check swiftmail and i like their plugin decorator when you are sending email to multiple recipient

**Comment by dudeami0** [comment]
How batch sending works in the class is:

Check if batch mode is enabled and needed.
First batch send To and CC headers along with the first BCC batch.
Continue to send the rest of the BCC batches (No To and CC headers sent)

It seems like it would be a lot of looping for large batches if the email was sent separately to each recipient. The only change I could think off would be seperating the To and CC batch from BCC batches (Else the first batch would see the To and CC, other batches would not).

**Comment by jschreuder** [comment]
@dudeami I won't get round to testing it, maybe Dan or Phil will but if they don't I'll take a look tomorrow.

First reaction: you didn't have to clean out the static methods in Email. Take a look at how Session works: it keeps 1 instance of a driver as a static property on which the static methods of Session itself work. Pretty much like yours used to work, but Email::factory() should still be able to return individual objects. That way you offer both simple usage through static methods and a way to do multiple emails using the objects returned by the factory (which is all Email can do currently).

If you put the old one back but keep your new factory() and rename $email_base to $_instance Email will be ready.
https://github.com/dudeami/fuel/blob/e1c42915a690c7e6fff18cb6b52a5a03f574078b/fuel/core/classes/fuel/email.php

**Comment by jschreuder** [comment]
(updated my comment as it wasn't clear what I meant)

**Comment by jschreuder** [comment]
It looks very good on my first read-through, but I've only been able to skim through the driver. As I've said I'll take a more extensive look tomorrow at the inner workings. From a Fuel-user standpoint I think it's pretty much done.

But I do have some pointers about coding style as your style doesn't yet match Fuel's:
- Curly brackets get a new line, both starting en ending (with the exception of the class decleration)
- Spaces around assignment operator =
- No spaces around concatenation operater .
- array() should be written all lowercase, same for "as" in foreachs
- Docblocks get more newlines within them, and use tabs. Check the current classes in the core for examples
- All classes get full docblocks about Fuel and the class itself

And one last suggestion: make the Driver class abstract and add an abstract method _send(), as that's a required method for all drivers.

Keep up the good work!

**Comment by dudeami0** [comment]
Added all the suggestions you made above.

**Comment by philsturgeon** [comment]
Sorry for the delay in merging this, you've been really patient with us. I'll test this out tonight properly.

**Comment by dudeami0** [comment]
I am personally in no rush to get this merged. I rather take it slow and make sure everything is done right and works as expected.

**Comment by philsturgeon** [comment]
Merged, thank you!

**Pull request merged**
