### PR TITLE
Remove git submodules and update composer.json to install submodules

### PR DESCRIPTION
**Pull request by kenjis**
See http://fuelphp.com/forums/discussion/13015/fuelphp-1-x-composer-setup

`composer.json` in this PR is for 1.7.2<del>, and needs tags "v1.7.2" of all sub repositories</del>.

To test this, change all <del>`"reference": "v1.7.2"`</del>`"reference": "1.7/master"` to `"reference": "1.8/develop"`

### CODE REVIEW

**Comment by WanWizard** [comment]
Thanks. I'll merge when I start preparing for v1.7.2.

I'm not sure the repo paths need to be excluded. git is smart enough to see they are repo's, and will not recurse into them. Downside of these exclusions is that if someone decides to make a single repo for deployment reasons by deleting the .git folders, the framework will still be excluded.

**Comment by it-can** [comment]
Nice... Maybe ignore the core and packages folders in .gitignore file?

**Comment by it-can** [comment]
How can i update composer to the latest 1.8/develop? And also get the latest commits?

**Comment by kenjis** [comment]
@it-can 

Change all `"reference": "1.7/master"` to `"reference": "1.8/develop"`, and `composer update`.

Once you've installed, if you want latest commits, you have to change all versions, in this case `"1.7.2"`.
So you have to change to, say, `"1.8.0"` or `"1.8.0.1"` or something.

This is limitation of Composer repository "package"

https://getcomposer.org/doc/05-repositories.md

> Note: This repository type has a few limitations and should be avoided whenever possible:
>         Composer will not update the package unless you change the version field.
>         Composer will not update the commit references, so if you use master as reference you will have to delete the package to force an update, and will have to deal with an unstable lock file.

**Comment by it-can** [comment]
@kenjis thanks

**Comment by WanWizard** [comment]
This has now been fully implemented, including the option to fetch fuel/fuel from packagist.

By default composer will install the latest master, if you ask composer to install a dev version, the latest develop will be installed from github.

**Comment by it-can** [comment]
Also for email / auth / orm / oil etc?

**Comment by WanWizard** [comment]
Nothing needs doing to them. You get fuel/fuel through composer, and it installs the rest.

**Comment by it-can** [comment]
But are the packages also 1.8/develop?

**Comment by WanWizard** [comment]
There is no need for composer packages for the other repo's. The composer.json in fuel/fuel will pull those in, either from the github zip file (for master versions) or using a git clone (for develop versions).

**Comment by it-can** [comment]
uuuhm... I see some errors... can you show me what I have to have in my composer.json file?

This error is shown btw (I use "fuel/fuel": "dev-1.8/develop"):

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fuel/fuel dev-1.8/develop -> satisfiable by fuel/fuel[dev-1.8/develop].
    - fuel/fuel dev-1.8/develop requires fuel/docs 1.7.2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by kenjis** [comment]
@it-can 
What do you want to do?

If you want to install Fuel with all 1.8/develop, now you can do it:

```
$ composer create-project fuel/fuel:dev-1.8/develop --prefer-source
```

**Comment by WanWizard** [comment]
And you can't install a master this way, not until 1.7.2 is released (the current master doesn't support this).

**Pull request closed without merging**
