### PR TITLE
Bootstrap upgraded to 2.3.2

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by WanWizard** [comment]
Did you check the impact of this on the Welcome controller and the views generated by the admin generator?

**Comment by sagikazarmark** [comment]
Yes, I am sure. I tested, however the admin generator has a few bugs which I will try to fix.

The changes in bootstrap which has effect on pages:
- The navbar has to have the `navbar-inverse` class in order to have dark background. The default is now light. (I can do this change)
- Some fonts are a bit bigger

**Comment by WanWizard** [comment]
I don't use oil generated code, so if you can check, correct and PR, that would be greatly appreciated.

**Comment by sagikazarmark** [comment]
Ok, I will check it.

2013/7/14 Harro Verton notifications@github.com

**Comment by WanWizard** [comment]
Thanks!

**Comment by sagikazarmark** [comment]
Hi,

I am back. Since we last talked Bootstrap has released a new version. How about upgrading to that version? Of course I can do that, but more work is needed.

What do you think?

**Comment by elvendor** [comment]
:+1: for Bootstrap 3

**Comment by WanWizard** [comment]
I don't have a problem with that, as long as everything is upgraded, including oil. And probably also a new bootstrap3 section in the pagination config if needed.

**Comment by sagikazarmark** [comment]
Ok. Starting to work on it.

**Comment by sagikazarmark** [comment]
From Bootstrap 3.0 responsiveness is integrated into the framework, however there are some tips for disabling this behaviour. Do you mind having Fuel Welcome, Hello, 404 page a responsive page?

**Comment by sagikazarmark** [comment]
About the pagination: I don't think that support for BS 2.x should be removed. I would rename it to bootstrap2 and apply the BS3 style for the default bootstrap config.

**Comment by WanWizard** [comment]
No, I don't mind. And I didn't say support for BS2 should be removed from pagination, but to add a new BS3 section. I would not rename it, that would break all apps that use it.

**Comment by sagikazarmark** [comment]
I am closing this since these commits has been removed.

**Pull request closed without merging**
