### PR TITLE
Pagination-changes-2

### PR DESCRIPTION
**Pull request by snrp**
Added more functionality to Pagination class.

It has 3 operating modes: 
- classic (exactly as before, it is the default, no need to adjust anything in the way you use it)
- segment_tag 
- get_tag

See bellow for what the new operating modes do and how to activate them.

<pre>
// fully backwards compattible
// by default it behaves exactly as before,
// if you want to use the new functionality
// then set $config['method'] (see bellow)

//------------------------------------------------------------------------------------

// 'method' => 'classic' (default - behaves exactly as before)
//  no need to do anything different
$config = array(
    'pagination_url' => \Uri::create(),
    'total_items' => 17,
    'per_page' => 5,
    'uri_segment' => 3,
);
Pagination::set_config($config);
echo Pagination::create_links();

//------------------------------------------------------------------------------------

// 'method' => 'segment_tag'
//      usefull if you want to put the pagination nr somwhere other at the end of the pagination_url string
// behaviour:
//      instead of being appended to the end of pagination_url, 
//      the page_nr is str_eplaced where the '{p}' is
// possible uses:
//      'pagination_url' => \Uri::create('monkeys/index/{p}/foo')
//      'pagination_url' => \Uri::create('monkeys/index/{p}?foo=bar')

$config = array(
    'pagination_url' => \Uri::create('monkeys/index/{p}?foo=bar'),
    'total_items' => 17,
    'per_page' => 5,
    'uri_segment' => 3,
    'method' => 'segment_tag',
    
    //hide the segment when page_nr == 1 
    //'hide_1' => false, //default = true
    
    //set the tag that will be str_replaced with the page_nr in the pagination_url
    //'replacement_tag' => ':page', // default ='{p}'
);

//------------------------------------------------------------------------------------

//'method' => 'get_tag'
//      usefull if you want to put the pagination nr in a $_GET variable
// behaviour:
//      the page_nr is str_eplaced where the '{p}' is
//      for example if 
//          pagination_url = 'monkeys/index?{p}', 
//      then the url for page 2 will be:
//          'monkeys/index?page=2' 
// in case 'hide_1' == true (default), for page 1 the page number will be omited from the link url by create_links:
//      'monkeys/index' 
//      instead of 
//      'monkeys/index?page=1' 
// the '?' and the '&' symbols in the url will be inteligently adjusted when hiding the page nr for page 1
// possible uses:
//      'pagination_url' => \Uri::create('monkeys/index?{p}')
//      'pagination_url' => \Uri::create('monkeys/index?foo=bar&{p}&foose=snoose')
// you get the point

$config = array(
    'pagination_url' => \Uri::create('monkeys/index?{p}&foo=bar'),
    'total_items' => 17,
    'per_page' => 5,
    'method' => 'get_tag',

    // set the get variable name:
    //'get_variable'  => 'pagina', //default = 'page'
    
    //hide the get variable when page_nr == 1 
    //'hide_1' => false, //default = true
    
    //set the tag that will be str_replaced with the page_nr in the pagination_url
    //'replacement_tag' => ':page', // default ='{p}'
);
</pre>

### CODE REVIEW

**Comment by snrp** [comment]
@CharlieBlack Yea... I had a verion before that relied on Uri::create, and you would set the get vars in pagination::get_variables, and then pass them to Uri ::create when creating the Uri, dont remember why I changed it...

I am getting tired of this pagination thing...

You are right, something like this would be more desirable:

Check out the pre-last commit. It now uses Uri::create.

Put this in your controller welcome if you want to test it:

```
public function action_index()
{
    //$this->render('welcome/index');

    $config = array(
        'pagination_url' => \Uri::create('welcome/index'),
        'total_items' => 17,
        'per_page' => 5,
        'uri_segment' => 3,
    );

    /*
    $config = array(
        'method' => 'segment_tag',

        //'pagination_url' => , // <-- not used
        'uri_segment' => 3, 

        'uri' => 'welcome/index/:page/', // <--- notice the colon (:)
        'get_variables' => array('foo' => 'bar' ),

        // 'variable_name' => 'page', // <--- notice NO colon (:)

        // hide the segment when page_nr == 1 
        // 'hide_1' => false, //default = true

        'total_items' => 17,
        'per_page' => 5,
    );

    */

    /*
    $config = array(
        'method' => 'get_tag',

        //'pagination_url' => '', // <-- not used
        //'uri_segment' => 3, // <-- not used 

        'uri' => 'welcome/index', 
        'get_variables' => array('foo' => 'bar' ),  

        // 'variable_name' => 'page', 

        'total_items' => 17,
        'per_page' => 5,

    );
    */

    Pagination::set_config($config);
    echo Pagination::create_links();
}
```

**Comment by snrp** [comment]
```
    //or like this:
    $config = array(
        'method' => 'segment_tag',


        //theese 3 will be passed to Uri::create as params:
        'uri' => 'welcome/index/:blah/:page/', 

        'variables' => array('blah' => 'segment_blah' ),

        'get_variables' => array('foo' => 'bar' ),


        'uri_segment' => 4,         
        'total_items' => 17,
        'per_page' => 5,
    );
```

For page 2 the link would be:

`http://localhost/fuel/public/index.php/welcome/index/segment_blah/2/?foo=bar`

**Comment by KaneCohen** [comment]
Looks very good. Have a lot of very much needed functionality. Hope it'll be commited.

**Comment by KaneCohen** [comment]
Found strange bug:
If i set two pagers on the same page, then if i set different "pagination_url" on second pager it won't display desired url, it'll use one, which i set on the first pager init.

**Comment by snrp** [comment]
@CharlieBlack thats bk it uses static::$pagination_url. So iwhen you set_config() it overwrites the static var - that is _not_ part of my modifications, it is part of the original class.

The way around that is to create_links() for pager 1 before you set_config() for pager2.

Also note that pagination_url is _not_ used in my extended modes but $uri instead (perhaps it should throw an error if you try to use it).

Note that I think I will close this pull request soon. 

If it is not merged into Fuel, you should stick to using the original Fuel::Pagination since you will not be able to get support for this version..

**Comment by snrp** [comment]
i made a simplified version . closing this

**Pull request closed without merging**
