### PR TITLE
Replacing git submodules with composer

### PR DESCRIPTION
**Pull request by lukearmstrong**
I stumbled across [composer/installers](https://github.com/composer/installers/) the other day, and I figured out how to use it to install core, modules and packages. I have submitted a PR to them [ https://github.com/composer/installers/pull/57 ] so that they can enable support, but you should be able to test what I have done as I have used [composer/satis](https://github.com/composer/installers/) to create my own temporary repository for installing composer packages.

[lukearmstrong/satis](https://github.com/lukearmstrong/satis) >> http://lukearmstrong.co.uk/satis/

```
lukea@ft02 
/var/www/fuel $ composer install
Loading composer repositories with package information
Installing dependencies
  - Installing fuelphp/upload (dev-master 7c8158a)
    Cloning 7c8158a71d690013f57e796ee8a287cb8b6b5c4a

  - Installing composer/installers (dev-fuelphp-support 7941e25)
    Cloning 7941e25f5ef72870337bbe427b302823e82c6a66

  - Installing fuel/core (dev-composer-installers cae0ffb)
    Cloning cae0ffba70fa87a3ee671aefd5a43b679c6f220b

  - Installing fuel/auth (dev-composer-installers 76ee813)
    Cloning 76ee813763fb6d4f35885c1f0b90f19c36eca2da

  - Installing fuel/email (dev-composer-installers 2233333)
    Cloning 223333377bcfdc7d13f381deedbda1fc04fb8dd7

  - Installing fuel/oil (dev-composer-installers 5da935e)
    Cloning 5da935e28e610ef46a70307d883620c8696114dc

  - Installing fuel/orm (dev-composer-installers c5d2787)
    Cloning c5d27874b2671098c349292b37acc4ae2a58b550

  - Installing fuel/parser (dev-composer-installers 920ed81)
    Cloning 920ed81a6b53e3cea8d7d4c1b1a5537b7141a7e4

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing monolog/monolog (1.3.1)
    Loading from cache

monolog/monolog suggests installing mlehner/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
Writing lock file
Generating autoload files
```

I have submitted 6 other PRs to you.

https://github.com/fuel/core/pull/1310
https://github.com/fuel/auth/pull/46
https://github.com/fuel/email/pull/36
https://github.com/fuel/oil/pull/168
https://github.com/fuel/orm/pull/216
https://github.com/fuel/parser/pull/64

I am aware that the PRs aren't correct, as the composer.json files point to my personal repository and my branches, but this is just so that you can simply clone and run `composer install` to see it work.

If you like the idea, all you need to do is add the `fuel/*` repositories to https://packagist.org/

As a fair bit of effort went into this, I would appreciate being able to fix these PRs to make them point to the packages on packagist once you have added them, so please don't rewrite my commits as I won't get any "credit" for my work.

### CODE REVIEW

**Comment by tomschlick** [comment]
:+1:

**Comment by peter-fritchley** [comment]
Good work :tada:

**Comment by phil-lavin** [comment]
:-1: 

:trollface:

**Comment by davispuh** [comment]
I've been using Fuel with composer for some while already. There isn't really any need to have `composer.json` in repo, but it would be useful

currently for my app:

``` javascript
{
    "name": "sample/example",
    "description": "example",
    "repositories": [
    {
        "type": "package",
        "package": {
            "name": "fuel/core",
            "version": "1.6-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/fuel/core.git",
                "reference": "1.6/develop"
            }
        }
    },
    {
        "type": "package",
        "package": {
            "name": "fuel/auth",
            "version": "1.6-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/fuel/auth.git",
                "reference": "1.6/develop"
            }
        }
    },
    {
        "type": "package",
        "package": {
            "name": "fuel/email",
            "version": "1.6-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/fuel/email.git",
                "reference": "1.6/develop"
            }
        }
    },
    {
        "type": "package",
        "package": {
            "name": "fuel/oil",
            "version": "1.6-dev",
            "source": {
                "type": "git",
                "url": "https://github.com/fuel/oil.git",
                "reference": "1.6/develop"
            }
        }
    }
    ],
    "require": {
        "php": ">=5.4.0",
        "monolog/monolog": "dev-master",
        "fuel/core": "1.6-dev",
        "fuel/auth": "1.6-dev",
        "fuel/email": "1.6-dev",
        "fuel/oil": "1.6-dev"
    },
    "minimum-stability": "dev"
}
```

**Comment by WanWizard** [comment]
I've seen the other PR's, but I can't say I'm happy with them. 

For starters, you're using the fuelphp-package type, which is the 2.0 package installer, which doesn't work in 1.x, because it will install the packages in the wrong path.

We WILL move to composer, but only after careful consideration, and maybe not for everything before 2.0.

**Comment by lukearmstrong** [comment]
Have you even tried it? It installs these repositories to these paths:

```
fuel/core   => fuel/core
fuel/auth   => fuel/packages/auth
fuel/email  => fuel/packages/email
fuel/oil    => fuel/packages/oil
fuel/orm    => fuel/packages/orm
fuel/parser => fuel/packages/parser
```

I assumed the `composer/installers` tool was to cater for installing things for frameworks before they adopted PSR and were able to use the `vendor` folder. Surely FuelPHP 2.0 shouldn't require a special type?

The `fuelphp-package` type didn't even exist before I added it to `composer/installers`.

If you prefer I could modify my PR to them so that the types are `fuel-core`, `fuel-module` and `fuel-package`. Leaving `fuelphp-package` still usable for FuelPHP 2.0.

**Comment by WanWizard** [comment]
I missed the reference to composer/installer, I tought you used the fuelphp installer, based on the package type. Which is specific to 2.0. (see https://github.com/fuelphp/package-installer). We haven't added anything to composer yes as it's still a work-in-progress (our current test package: https://github.com/fuelphp/demo-package)

Perhaps you should indeed change it to "fuel", as that is the "vendor name" used for the 1.x train, where as we use "fuelphp" for 2.0.

**Comment by lukearmstrong** [comment]
I've renamed the type from `fuelphp-*` to `fuel-*`
https://github.com/composer/installers/pull/57

I've also made these changes to all of the other repositories...
https://github.com/fuel/core/pull/1310
https://github.com/fuel/auth/pull/46
https://github.com/fuel/email/pull/36
https://github.com/fuel/oil/pull/168
https://github.com/fuel/orm/pull/216
https://github.com/fuel/parser/pull/64

**Comment by lukearmstrong** [comment]
`fuel-module` and `fuel-package` have been merged into `composer/installers`.

https://github.com/composer/installers/pull/57#commit-ref-c686733

`fuel-core` hasn't yet, but hopefully will be soon.

**Pull request closed without merging**
