### PR TITLE
Remove comment before 'orm'

### PR DESCRIPTION
**Pull request by sdrdis**
Since oil generate a code which need the orm package, and since we will generally use this package on FuelPHP, I suggest to remove the comment before 'orm'...

### CODE REVIEW

**Comment by crynobone** [comment]
oil can generate model using Model_Crud which doesn't require Orm package, and it optional to use Oil Generate feature so it might not be use in all FuelPHP installation.

**Comment by sdrdis** [comment]
ok that holds, maybe oil should use crud by default then, but it is strange to use the generate feature and not to have something working at the first place :).

**Comment by jschreuder** [comment]
As of v1.1 Model_Crud is the default.

**Comment by sdrdis** [comment]
I submitted a pull request to oil package since it doesn't use Model_Crud by default (php oil g scaffold <modelname> is equivalent to php oil g scaffold/orm <modelname> and not php oil g scaffold/crud <modelname> as mentionned on the generate.php comments...).

**Comment by jschreuder** [comment]
My bad, it had defaulted to crud for a while in the dev branch but apparently has been switched back to ORM. Phil explained why in the pull request you made.

**Comment by sdrdis** [comment]
ok I just saw it. No problem, like it has been said it is not a big issue anyway :).

**Pull request closed without merging**
