### PR TITLE
fix on sign-off tip

### PR DESCRIPTION
**Pull request by kenjis**
Can't override original git command.

> To avoid confusion and troubles with script usage, aliases that hide existing git commands are ignored. 
> http://git-scm.com/docs/git-config

### CODE REVIEW

**Comment by frankdejonge** [comment]
Good call, I just don't know if "ci" will be the best shortcut for it. I think "cs" would be better, as it would represent "Commit Signed".

**Comment by WanWizard** [comment]
Any update on this one?

**Comment by kenjis** [comment]
I did something wrong, so I close this PR.
I'll send another PR.

**Comment by kenjis** [comment]
I sent https://github.com/fuel/fuel/pull/271

**Pull request closed without merging**
