### PR TITLE
Some tests to the Arr class

### PR DESCRIPTION
**Pull request by fesplugas**
Examples for the tests have been taken from the documentation, so maybe in the future we can even use the tests for creating the documentation examples.

Please, feel free to comment/suggest whatever you want on the tests.

### CODE REVIEW

**Comment by fesplugas** [comment]
Added more tests ...

**Comment by fesplugas** [comment]
Initial tests for the Html class and a fix for a missing variable.

**Comment by fesplugas** [comment]
Still learning ...

**Comment by fesplugas** [comment]
Last commit is a proposal feel free to ignore it. The good thing is that there are tests for that.

**Comment by jschreuder** [comment]
Accepted everything but the last commit, not really my area of expertise. Thanks for all the tests, good thing to get those going.

Next time only put related commits in the same branch, it's easier to merge when we can just accept the whole thing for a single branch and can decide other features seperately.

**Pull request closed without merging**
