### PR TITLE
Image Library

### PR DESCRIPTION
**Pull request by dudeami0**
Adds an image library that is able of manipulating images with GD or ImageMagick. If there is anything that needs changing or fixing, let me know.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Hey dudeami, this looks absolutely brilliant and I look forward to merging it in to Fuel, but there are a few small things first.

Firstly this looks like it has been merged with recent fuelphp changes manually. This means it will conflict a lot when we try to merge this. Could you possibly wipe this repo clean and just commit the image class and documentation changes?

Secondly there seems to be quite a few methods such as initialize, instance, factory and load, etc. These could probably be simplified somewhat.

factory() should take a filename and optionally some config such as which driver, etc (otherwise config is assumed from the image config file).

If anything needs to be run when the Image class is first referenced (and autooaded) we use _init() to emulate the behaviour of __constructor().

With load() would you not just create a new object instance via factory() to work with?

Good work though, these questions are just to ensure everything is the best it can be before it becomes part of the core.

**Comment by dudeami0** [comment]
Well, I did forget to add something to the code (Thanks for reminding me!) that allows running the same queued actions to several images. Right now it just requires adding a config value and putting an if statement around $this->clear_queue calls. An example is:

```
Image::factory(array(
    'clear_queue' => false
))->crop_resize(200, 200) // Create the queued actions
// Call these actions on all the following files.
->load('/old/path/upload1')->save('/new/path/upload1')
->load('/old/path/upload2')->save('/new/path/upload2')
->load('/old/path/uploadN')->save('/new/path/uploadN');
```

1) For the merge, I only needed to modify fuel/core/bootstrap.php, but I can clear out all the unmodified files.

2) I'll simplify those methods.

3+4) I'll change that

5) I believe that these two methods should stay separate. factory() creates a new instance of the Image_Driver class, while the load() is to load a new file for editing, and their more effective separate. If it should be changed, the queue would also have to be passed to the new instance, either through an additional param or the config for use with the code above. The option to add a $filename param to the factory is a good idea though, and I'll add it.

**Comment by dudeami0** [comment]
For 2, I renamed initialize to config (As that's what it does :p) and the other I left alone. load() loads the file and is separate from factory() because one loads a new instance of the class, and the other loads an image file to be edited. For the instance() method, that should be protected and is used for creating an instance for static use of the class.

For 3, done

For 4, There seems to be a problem with using _init(), and I think it might be the fact that the __construct is for use when an new instance is created, not when the classes are autoloaded. If I'm doing it wrong let me know.

I'll remove all the unmodified files and sent in another commit. I also added support for the code I made in the previous comment :)

**Comment by dudeami0** [comment]
Closing this request (Cleaned up the old repo, going to do another pull request)

**Pull request closed without merging**
