### PR TITLE
Update bootstrap.php

### PR DESCRIPTION
**Pull request by JoaoVagner**
Resolved my problem autoload failed on executed project in browser.

### CODE REVIEW

**Comment by JoaoVagner** [comment]
Hi @WanWizard my problem related in IRC, my resolution is this ;)

**Comment by kenjis** [comment]
`autoloader.php` is required in `index.php`
https://github.com/fuel/fuel/blob/1.7/master/public/index.php#L44

Why do you need this PR?

**Comment by kenjis** [comment]
By the way, would you please read https://github.com/fuel/fuel/wiki/Contributing before sending PR?

Your PR has no sign-off, coding standard violations, and sent to wrong branch (should be sent to `1.8/develop`).

**Comment by WanWizard** [comment]
This should indeed not be needed.

For normal request, it is loaded in `index.php` as @kenjis correctly says, for unit tests, it is loaded in `phpunit_bootstrap.php`, as indicated by your `phpunit.xml` file. 

If you have a problem with the autoloader being loaded twice, you need to look at yout local setup.

**Pull request closed without merging**
