### PR TITLE
Put back abstract class extension files

### PR DESCRIPTION
**Pull request by jschreuder**
Because otherwise they would be extended non-abstract and throw errors because the eval'ed class alias doesn't implment the abstract methods.

This shouldn't be necessary I think, we could decide to use convention and postfix or prefix all abstract classes with "Abstract" like DB_Abstract instead of DB_Driver or the more flexible DB_DriverAbstract & DB_ResultAbstract. But I'll leave that up to you. In the mean time this commit should solve any problems created by the current situation.

### CODE REVIEW

**Comment by isaiahdw** [comment]
Or just make eval() alias the abstract classes correctly like Kohana 2.x did. See: http://dev.kohanaframework.org/projects/kohana2/repository/entry/trunk/system/core/Kohana.php#L764

**Comment by jschreuder** [comment]
You're right, it will require some speed testing though as I've read Reflection is very resource heavy. The whole point of using eval() instead of extension in files was to save some resources, it would be a shame if Reflection would cost us some of those savings. Doing it by convention instead, using a "Abstract" postfix might be cheaper with substr($class, -8) == 'Abstract'.

Don't know why but I got it in my head Reflection was introduced with PHP5.3 instead of 5.0.

**Comment by isaiahdw** [comment]
Yeah I'm sure it will slow things down a lot (compared to not using reflection at all). However the speed improvements from using eval() vs loading the extra file (empty classes) is really non-existent, in fact it might actually be harmed a little. That's because in production you are always going to use op-code caching like APC. eval() can't be cached and the extra file include from the empty class can be, so in real production testing there is no advantage to not having the empty files. It can be nice for keeping things cleaner looking though.

**Comment by jschreuder** [comment]
I'm also a fan of the cleaner arguement. But to get to the speed arguement that it's useless in that respect because it doesn't work with op-code caching: until the next version of PHP after 5.3 that's not available to many yet. While any bigger sites have to have APC, it will be a big speed improvement to the far larger group of smaller site that don't have access to APC. Furthermore while I gotta admit I know little about op-code caching, as far as I know it only caches the files's compiled code - it doesn't put cache files together. Which means there's still a cost in including other files, and thus it's not necessarily less expensive then parsing a single line of uncached code.

**Comment by jschreuder** [comment]
Dan has solved this using Reflection after speed testing showed it doesn't add anything to worry about to loading performance.

**Comment by isaiahdw** [comment]
Good to see it got fixed.

I didn't mean APC would merge everything into one file. The reason you will see poor performance when using APC (with eval() autoloading) is because every time you autoload a file it will have to run the php parser for eval() to work. APC will also cache the compiled (op-code) file in the memory so the extra include ends up costing very little compared to starting up the php parser just to run eval().

Either way this isn't a big deal because when performance matters you can always add the empty class files back and avoid the eval call. Just thought explaining a few of the reason why Kohana doesn't do it this way anymore might be helpful :)

**Pull request closed without merging**
