### PR TITLE
Adding Transaction Functionality

### PR DESCRIPTION
**Pull request by five07**
This adds the same transactional functionality to \Fuel\Core\Database and driver as I added to the MySQLi driver.

http://fuelphp.com/forums/topics/view/386
http://fuelphp.com/forums/topics/view/407

Also patched MySQL & MySQLi behavior to only log transaction errors for non INSERT queries

### CODE REVIEW

**Comment by five07** [comment]
Adding \Fuel\Core\Database_Transaction with recommendations from Phil to make database agnostic

http://fuelphp.com/forums/topics/view/407#1

Added the necessary functionality to the existing database drivers

**Comment by philsturgeon** [comment]
This is great work, thank you so much for sending a pull request and making this generic. Transactions are one of the main things we were missing, so this rocks! :)

If it would not be taking "the mick" even more, do you think you could document this? We can add some blank Database files for you and do some of the methods, or you can just copy from another class and document your methods.

**Comment by philsturgeon** [comment]
Ignore that, this is likely to be pulled before a big DB reshuffle. We'll document it when its all done.

**Comment by dhrrgn** [comment]
Great work.  It has been merged.

**Comment by five07** [comment]
Phil,

I'd be happy to not only document the transaction class, but the entire Database class as well. Would you prefer I fork the main fuel/docs repo or just add to the docs in this branch?

**Pull request merged**
