### PR TITLE
Recommend Parser dependencies in composer.json, update submodule

### PR DESCRIPTION
**Pull request by bobthecow**
This change goes with fuel/parser#62

### CODE REVIEW

**Comment by bobthecow** [comment]
Thanks!

**Comment by WanWizard** [comment]
You did check that the View extensions (for Twig and Smarty) still work with the switch to the composer package?

**Comment by bobthecow** [comment]
Yep. I tested it with Mustache, Twig and Smarty. All you have to do is add `mustache/mustache`, `twig/twig` and `smarty/smarty` to your `composer.json` and install.

Well, that and add `parser` to your `always_load.packages` package config... That could have been a bit clearer on the Parser docs page :)

**Comment by WanWizard** [comment]
Cool! Thanks!

I've updated that section of the docs.

**Comment by bobthecow** [comment]
Awesome. Thank you.

**Pull request merged**
