### PR TITLE
Moved public asset index.html files to .gitkeep

### PR DESCRIPTION
**Pull request by dmyers**
Moved public asset index.html files to .gitkeep in favor of web server handling directory indexing.

What do you think?

### CODE REVIEW

**Comment by WanWizard** [comment]
The files were put in there just to avoid that. There are plenty of installs where DirectoryIndex has not been disabled.

**Comment by dmyers** [comment]
It looks like b624c8be807c6e75fd7448294be3d209d006b647 changed it so directory indexing is disabled in .htaccess.

**Comment by WanWizard** [comment]
Yeah. 

But not everyone uses the default .htaccess. Some people need to be protected against themselfs... :smile:

**Comment by Lofwyr23** [comment]
The standard .htaccess broke on Apache 2.4 (at least on win7, couldn't be arsed to compile apache by hand on debian <-<), because Options have to be set in the matching directory block now... so a rewrite might be handy ;E

**Pull request closed without merging**
