### PR TITLE
Output Buffering & app stats

### PR DESCRIPTION
**Pull request by lonnieezell**
I've wrapped the app execution into an output buffer, and added a finish() method to fuel/core which grabs the output buffer and replaces {memory_usage} and {elapsed_time} in the buffer before displaying, like CodeIgniter does, so that we can get a basic performance record as we develop.

### CODE REVIEW

**Comment by philsturgeon** [comment]
Not sure I like having {elapsed_time} and whatnot, I feel it will confuse people about the parser.

Could you instead use the benchmark lib? Using Static classes (helpers) in the view should not be discouraged, to me its clean enough.

**Comment by lukeholder** [comment]
i agree phil... helper functions not another parser.

**Comment by lonnieezell** [comment]
I understAnd the worry about the parser. 

The reason I went this route is that once you are using caching on pages, the Benchmark would also be cached. It is using the Benchmark lib for the values currently, it just inserts them prior to rendering to make it cache safe.

I suppose one other option would be to just include that info in a profiler report, if Fuel is getting some form of profiler.

**Comment by lukeholder** [comment]
if a page has been cached is knowing the elapsed time so important? maybe. i would think that elapsed time would be most important during development and not production.

**Comment by lonnieezell** [comment]
I agree it's most important during development. I just like to be able to measure the entire process. If it doesn't work on a cached page, then the only metric available is the before caching time. There's no way to measure the improvement. Or make sure you didn't put in a hook or something that is executing prior to caching, or fine-tune Fuel's performance, or even fine-tune your production server's APC or XCache settings. 

I guess at this point, it's really kind of moot, since Phil already disabled it, though. :)

**Comment by philsturgeon** [comment]
We can look into adding this back in as some kind of global data available in the view, or something, but for now I don't think we really need it. Especially not with the current syntax.

**Pull request closed without merging**
