### PR TITLE
 ActiveRecord\Model::to_options_list() and  Form::options_list();

### PR DESCRIPTION
**Pull request by snrp**
added ActiveRecord\Model::to_options_list() and Form::options_list(); Both return an options array that can be passed to Form::select()

### CODE REVIEW

**Comment by jschreuder** [comment]
Dan is currently doing some work on AR, so merging now isn't possible.

Having said that I think you're on the right track but took the wrong approach on the Model::to_options_list() function. It shouldn't be named Form class specific, it just outputs an associative array and it should be named as such because it can be used for much more: Model::get_array() or something similar.

The form class method too is kinda nice but fails far to harshly, using Error::notice() and just continue on a failed object/array would be better. I gotta think about that one though, if it really belongs in the core.

**Comment by snrp** [comment]
@jschreuder I thought of putting the Form::options_list() in class Arr::something(), but I couldnt think of a suitable name for it.

Arr::md_to_kv_list() ? md_to_list ? collection_to_list ? I think we have a winner.

**Comment by huglester** [comment]
earlier I saw it like: Model_Users::dropdown();

For me it was a nice name. not sure about here

But it's very helpful funciton

**Comment by jschreuder** [comment]
The whole DB/ORM thing is very much being evaluated right now as I mentioned earlier, so I'm closing this but I do have it written down for when a new or rewritten ORM/AR is developed.

**Pull request closed without merging**
