### PR TITLE
Session classes

### PR DESCRIPTION
**Pull request by WanWizard**
implemented singletons for session drivers
implemented dot-notation for get() method (so they behave like the config methods)

### CODE REVIEW

**Comment by jschreuder** [comment]
I'm wondering if it's necessary to treat them as singeltons? If the cookie name differs can't you use multiple drivers of the same kind? (might be usefull for allowing both frontend & backend users with different sessions)
If I'm right you could have the instance identifier default to the standard config but use the cookie name if that was set in config with a different value than te default one..? That wouldn't change anything but the instance id determination I think?

Also one minor nitpick point: at lines 108-112 you test if there's an init() method. But as the init method is part of your abstract driver you can expect it to always be there. Even if someone were to create a driver that doesn't extend the abstract driver they'd still have to adhere to the interface set forth by the abstract to have everything work as expected.

EDIT: Oops, didn't mean to close it.

**Comment by WanWizard** [comment]
technically it's not necessary, but that means every storage driver needs a method to validate all configuration fields that need to be different from the instances already loaded, and it needs to check every already loaded instance of that driver for a config collision. Depending on the driver it's much more than only the cookie name. You can't have two instances poking around in the same database table for example.

The init() check is a leftover, and can be removed now that it's a required method(). I'll remove it.

**Comment by jschreuder** [comment]
I took a quick look into the DB driver but I couldn't think of a reason it would be a problem. If I'm not mistaken only the session ID and the cookie name run the risk of collision right? The session ID cannot reasonably collide because of the sheer number of random possibilities (just as likely on the same computer as on differnet ones). So it should be only the cookie name that can collide right? Or am I missing something?

I'll pull the changes btw, but if possible I'd still like the session drivers to be non-singleton.

**Comment by WanWizard** [comment]
Checking one value is the same complexity as checking more. I'll see what I can do.

**Pull request closed without merging**
