### PR TITLE
Updated oil to remove carriage return.

### PR DESCRIPTION
**Pull request by hrabbit**
Was printing a carriage return which causes schedulers (eg. cron) to output a carriage return on every run even if not wanted.

### CODE REVIEW

**Comment by philsturgeon** [comment]
This needs to be in there so when you finish any other task or function using Oil it wont show the prompt on the same line as the output.

**Comment by hrabbit** [comment]
Phil, shouldn't that be up to the discretion of the developer rather than the oil process itself?

**Comment by philsturgeon** [comment]
Sure, but we'll need a pull request that adds a carriage line to every place in oil that needs it AND a note in the changelog that people will need to update their code before we can merge this one :)

**Comment by hrabbit** [comment]
Makes sense.. No promises.. I'll see if I can spare some time for it.

**Pull request closed without merging**
