### PR TITLE
Update composer.json and readme to PHP 5.4. Also, fix some typos

### PR DESCRIPTION
**Pull request by findrakecil**
Hello, I want to propose some changes for `composer.json` and `README.md` files:

### composer.json

- Update PHP version to 5.4 in `composer.json` require and description.

### README.md

- Fix some typos
- Update PHP version in description
- Fix some FuelPHP links

### CODE REVIEW

**Comment by WanWizard** [comment]
I can live with this, ideally I would like to bump it to 5.6, but I got quite a bit of opposition...

**Comment by findrakecil** [comment]
Well, the reason I use version 5.4 is because the website said that FuelPHP is based on PHP 5.4+

So, I just want to make it consistent 😄 

If the website is updating the PHP version, maybe I will update it too

**Comment by WanWizard** [comment]
Ah, someone noticed we've been trying to get rid of the PHP 5.3.3. that's been there for ages... :smile:

**Comment by willpoorman** [comment]
All for bumping up PHP versions as long as it's on newer versions of the framework! Some people get stuck in environments that they can't upgrade the installed version of PHP on. So if they use Fuel 1.8 because they know it supports their version of PHP, and then that version gets an update to bump the PHP version, that can break a lot of things.

**Comment by WanWizard** [comment]
That seems logical, no changes will be done retroactively.

**Pull request merged**
