### PR TITLE
Adding the full path to php in oil executable

### PR DESCRIPTION
**Pull request by fabioluciano**
When you need to put a oil refine to a cronjob you need to put the full path of oil executable. But, the script doesnt "know" how to execute it. I added the "#!/usr/bin/php", in the file to get this fixed.

### CODE REVIEW

**Comment by fabioluciano** [comment]
To find the porpose to the modification, try to call the refine out of the project folder. and if you call the full path to oil, you've got some errors:

/media/serv/php/xxx/oil: linha 1: ?php: Arquivo ou diretório não encontrado
/media/serv/php/xxx/oil: linha 2: /bin: É um diretório
/media/serv/php/xxx/oil: linha 3: CHANGELOG.md: comando não encontrado
/media/serv/php/xxx/oil: linha 4: docs/: É um diretório
/media/serv/php/xxx/oil: linha 5: erro de sintaxe próximo do `token' não esperado`-1'
/media/serv/php/xxx/oil: linha 5: `error_reporting(-1);'

**Comment by gizzmo** [comment]
oil is a php file, you need to pass it to php, just like it shows in the docs. Also i have little experience with cronjobs, but cant you just set it up to call php with oil `path/to/php path/to/oil` or even just `php path/to/oil`?

**Comment by fabioluciano** [comment]
Yes, oil is a php file. But in the context of command line, doesn't. If you don't use the shebang, to specify the interpreter, it doesn't make sense. Do you agree?

If the file is a php file, why not use shebang to specify it? Is just a question of security of which interpreter will be in use.

**Comment by gizzmo** [comment]
I was able to get oil to work just fine when not in the directory oil is in. The only real plus is that you dont have to pass it though php. 

One reason not to use the 'shebang' is a user would **have to** edit oil if their php is not in `/usr/bin`. I use 'git on windows' and i don't think that 'shebang' will work.

**Comment by fabioluciano** [comment]
I need to agree with you. I forgot the windows users. But i need to say:
- In the most linux distros, the binary of php are in the same place. a.k.a '/usr/bin/php'.
- When you say 'git for windows', should meant what? We are talking of php and 'shebang'.

**Comment by gizzmo** [comment]
Yes in Linux it is normally in `/usr/bin/` but they could be using xampp, or some other package that puts php in a unique location. Mainly what im saying it is seems easier for everyone to just pass oil to php, and i think the developers feel that way too since they made it that way to start.

And by 'git for windows' i mean i dont use the windows cmd.

**Comment by jschreuder** [comment]
This is OS and even installation specific code as @gizzmo pointed out. Also it's mentioned in all the docs you should call `php oil`, thus this is not desireable in the core. Adding a note to docs on how to modify this locally might be nice though...

**Pull request closed without merging**
