### PR TITLE
Allow required field errors to pop up even when input array and $_POST array are empy.

### PR DESCRIPTION
**Pull request by frankdejonge**
Moved 'return false on empty input' further down to allow required field errors to pop up. Now it returns false on empty, without any errors.

### CODE REVIEW

**Comment by frankdejonge** [comment]
Wil open a new one with just the validation pull, truncate was already pushed.

**Comment by jschreuder** [comment]
This will cause errors to show even when there was nothing to validate, that's the reason why it won't validate on empty input.

[edit] In other words: it would validate before the form was even submitted, which is useless.

**Comment by frankdejonge** [comment]
Yes, which is the point. You don't run the validation unless there is something to ckeck. But I think that logic should be outside of the 'run' function. How wil you check against empty form posts?

**Comment by jschreuder** [comment]
When a form was empty on submit, `$_POST` will still have all the fields with empty values so `empty($_POST)` will return false in that case.

This prevents errors from being given when nothing was given to validate, it will return false but not validate. When an empty form was submitted the `$_POST` superglobal will contain a couple of empty values and it will validate it all.

**Comment by philsturgeon** [comment]
I can see both sides here but I am inclined to agree with Jelmer. How often do you actually have an empty form? At the very least the submit button will be in there.

When creating a self submitting form this would be a pain, and would need you to wrap it in an extra if (Input::post()) which I think is probably unnecessary.

**Comment by frankdejonge** [comment]
Ah yeah, I see. My bad. Thanks for the quick response anyway!

**Comment by frankdejonge** [comment]
@phill yeah, the wrapping in the Input::post stuff is what i would have done in CI most of the times. But when there is no post data, nothing has been submitted, empty or filled. So this is right.

**Comment by dhrrgn** [comment]
Going to throw my 5 cents into the ring here (my opinion is worth more :P)

I am going to propose changing how it checks for no input.  Instead of doing this:

```
if (empty($input) && empty($_POST))
```

Do this:

```
if (empty($input) && \Input::method() != 'POST')
```

That way even if the form was completely empty (i.e. ajax form submission with no fields) it will still run validation because it will still be a POST request.

**Comment by frankdejonge** [comment]
Nice. For what's worth i'm all in for this one. It's practical ánd correct in theory.

**Comment by dhrrgn** [comment]
Actually...after thinking, we should probably do it like this:

```
if (empty($input) && \Input::method() == 'GET')
```

Theory behind this is that a PUT or DELETE request could still need validated, so only skip validation on GET requests.

**Comment by frankdejonge** [comment]
There is still just one problem here. What if there are 2 forms on the page handled by the same action. (could be the case) then the errors would still be thrown at the one run when submitting the other. So maybe the Input::post wrapper is not the worst option after all? Another option would be to have a keytrigger. Like Validation::run($trigger = 'submit_field',$input = array())?

**Comment by frankdejonge** [comment]
Another problem is also.. Inserting data is not only for users but also for 'sys-actions' so there might be an atomated validation (like in ORM) when there is an GET method.

-- stupid, then there would be an $input, doh

**Comment by dhrrgn** [comment]
Freaky: During both of those scenarios, the input would be sent to the run() method, so it would not be empty() and still run through validation, even on a GET.

**Comment by jschreuder** [comment]
I agree with the proposal but I think it's best to check for post as the Validation class will use either the given $input or POST. While it's correct from the HTTP point of view this would suggest the validation class will actually do stuff it can't.

**Comment by dhrrgn** [comment]
Jelmer, ya, but the end developer doesn't care how run() determines if it should run or not...as long as it runs when it is supposed to and not when it isn't.

**Pull request closed without merging**
